name: Javadocs

on:
  push:
    branches: [ master ]

jobs:
  javadocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unshallow
        run: git fetch --unshallow --quiet
      - name: Generate Javadocs
        run: mvn install javadoc:aggregate-no-fork
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
